name: ride_sharing_user_app
description: A ride sharing Flutter project.
version: 2.7.0+30
publish_to: 'none'

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.8
  #get: ^4.7.2
  get: #^4.7.2
    git:
      url: https://github.com/luis901101/getx_fork.git
      ref: old-4.7.0
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  http: ^1.5.0
  connectivity_plus: ^7.0.0
  firebase_core: ^4.2.1
  firebase_messaging: ^16.0.4
  flutter_local_notifications: ^21.0.0
  path_provider: ^2.1.5
  image_picker: ^1.2.0
  country_code_picker: ^3.4.1
  dotted_border: ^3.1.0
  percent_indicator: ^4.2.5
  url_launcher: ^6.3.2
  flutter_html: ^3.0.0-beta.2
  pin_code_fields: ^9.1.0
  flutter_svg: ^2.2.2
  shimmer_animation: ^2.2.2
  file_picker: ^10.3.3
  permission_handler: ^12.0.1
  syncfusion_flutter_datepicker: ^32.2.8
  google_maps_flutter: ^2.14.0
  geolocator: ^14.0.2
  flutter_animarker: ^3.2.0
  carousel_slider: ^5.1.1
  shimmer: ^3.0.0
  loading_overlay_pro: ^2.1.1
  modal_bottom_sheet: ^3.0.0
  flutter_widget_from_html_core: ^0.17.0
  flutter_typeahead: ^5.2.0
  dotted_line: ^3.2.3
  autocomplete_textfield: ^2.0.1
  flutter_inappwebview: ^6.1.5
  cached_network_image: ^3.4.1
  flutter_spinkit: ^5.2.2
  dart_pusher_channels: ^1.2.3
  flutter_switch: ^0.3.2
  just_the_tooltip: ^0.0.12
  speech_to_text: 7.3.0
  app_links: ^7.0.0
  share_plus: ^12.0.1
  video_thumbnail: ^0.5.6
  video_player: ^2.10.0
  chewie: ^1.13.0
  firebase_auth: ^6.1.2
  phone_numbers_parser: ^9.0.16
  flutter_keyboard_visibility: ^6.0.0
  location: ^8.0.1
  flutter_contacts: ^2.0.1
  expandable_menu: ^0.0.5
  flutter_slider_drawer: ^3.0.2
  receive_sharing_intent: ^1.8.1
  in_app_update: ^4.2.5
  package_info_plus: ^8.0.0
  #receive_sharing_intent: ^1.8.1
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/language/
    - assets/svg/
    - assets/map/
    - assets/webp/
    - assets/webp/slide_one.webp
    - assets/webp/slide_two.webp
    - assets/webp/slide_three.webp
    - assets/webp/slide_four.webp

  fonts:
    - family: SFProText
      fonts:
        - asset: assets/font/sf-pro-text-light.ttf
          weight: 300
        - asset: assets/font/sf-pro-text-regular.ttf
          weight: 400
        - asset: assets/font/sf-pro-text-medium.ttf
          weight: 500
        - asset: assets/font/sf-pro-text-semibold.ttf
          weight: 600
        - asset: assets/font/sf-pro-text-bold.ttf
          weight: 700
        - asset: assets/font/sf-pro-text-heavy.ttf
          weight: 900

    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
        - asset: assets/font/Roboto-Black.ttf
          weight: 900
